name: aoc_2024_dart
description: Advent of Code in Dart.
version: 0.1.0
repository: https://github.com/Wilhelmsson177/aoc-2024-dart

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  dotenv: ^4.2.0
  logging: ^1.2.0
  quiver: ^3.2.1
  talker: ">=3.1.4 <5.0.0"
  timing: ^1.0.1
  tuple: ^2.0.2
  path: ^1.8.0
  dart_console: ^1.2.0
  dartx: ^1.2.0
  equations: ^5.0.2
  dart_numerics: ^0.0.6

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  lints: ^3.0.0
  test: ^1.21.0
